name: Scrape, Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tjek repo ud
        uses: actions/checkout@v4

      - name: Sæt Python op
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer Python dependencies
        run: pip install requests beautifulsoup4

      - name: Kør scraper
        run: python3 scraper/ao_scraper.py

      - name: Sæt Node op
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer dependencies
        working-directory: web
        run: npm ci

      - name: Byg webshop
        working-directory: web
        run: npm run build

      - name: Deploy til simply.com via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SIMPLY_HOST }}
          user: ${{ secrets.SIMPLY_USER }}
          pass: ${{ secrets.SIMPLY_PASS }}
          localDir: web/out
          remoteDir: public_html
          options: --reverse --delete --verbose
